name: please work issue

on:
  issues:
    types: 
      - opened


jobs:

  pleasework:

    runs-on: ubuntu-latest

    
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
