name: Test Azure Credentials

on:
  workflow_dispatch:
  
jobs:
  test-credentials:
    name: "Test Creds"

    runs-on: ubuntu-latest
    
    steps:
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
