name: workflow-A

on:
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    uses: mickeygoussetorg/advanced-github-actions-presentation-reusable-workflow/.github/workflows/workflow-B.yml@main
    with:
      username: Elvis      
      
  my-personal-job:
    runs-on: ubuntu-latest
    needs:
      - use-reusable-workflow
    steps:
      - name: please work
        run: echo "please work"
  
