name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    
      - uses: mickeygoussetorg/advanced-github-actions-presentation/.github/workflows/workflow-B.yml@main
        with:
          username: Elvis
  
      - name: please work
        run: echo "please work"
  
